### ISSUE TITLE
Use EventTarget instead of `@scena/event-emitter`

### ISSUE THREAD

**Issue by DerZade** [daybrush/gesto#3]
Considering that this library will only be executed in a browser, you could use the browser-native [`EventTarget`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget) instead of `@scena/event-emitter` to save the extra Bytes. 

---

PS:

I know we're talking about maybe one KB when gzipped, but that's still over[ 5%  of the total size](https://bundlephobia.com/package/gesto@1.7.0).
Tbh, I was just wondering about the reasons for preferring a third-party package instead of already existing APIs.

---

PPS: Thanks for the amazing lib. ❤️ I also tried a few alternatives and gesto was the only one that worked flawlessly on the first try.

**Comment by daybrush** [comment]
@DerZade 

thanks. There are many concerns about the size. But I made `@scena/event-emitter`. and since my many libraries use event-emitter, it is difficult to change.

**Comment by DerZade** [comment]
Thanks for the clarification 🙈
