### ISSUE TITLE
Simultaneous dragging and pinching

### ISSUE THREAD

**Issue by DerZade** [daybrush/gesto#4]
My use case is pretty simple: I want to make a WebGL2 canvas pan- / zoomable using Gesto.

While doing some tests on my tablet I noticed a small problem: Gesto doesn't recognize a transition from dragging to pinching. This sounds like a fairly minor issue, but usability for my use case suffers greatly. Take the following example:
The user wants to pinch. The first finger is placed on the screen. The user slips a little and accidentally moves the finger by a few pixels. The second finger is placed with a slight delay. At this point , however, Gesto is already in "drag"-mode because the user has moved the first finger a few pixels and therefore completely ignores the second finger and pinch movement. 

Is there a way to enable Gesto to transition from dragging to pinching?

**Comment by daybrush** [comment]
@DerZade 

Use `pinchThreshold` option. 

The higher the `pinchThreshold` value, the more you can avoid slipping mistakes.

**Comment by DerZade** [comment]
> @DerZade
> 
> Use `pinchThreshold` option.
> 
> The higher the `pinchThreshold` value, the more you can avoid slipping mistakes.

Thanks a lot for the quick response. Setting `pinchThreshold` to a really big value (like `1000`) improved the problem, although it didn't solve it in its entirety.
Switching from drag to pinch, works flawlessly now, but switching back (from pinch to drag) does not:
1. Use one finger to drag -> `dragStart` event triggers
2. Place second finger on screen -> `pinchStart` event triggers
3. Lift second finger off screen -> `pinchStop` **and `dragStop`** events trigger

Imho only `pinchStop` should be emitted, but the dragging should continue 🤔.

--- 

PS: What exactly is `pinchThreshold`? I couldn't find any documentation for the options. Is it the amount of pixels I can drag, before starting a pinch?

**Comment by daybrush** [comment]
@DerZade 

Prevents pinching when the drag is moved more than a certain distance. That distance allowance is `pinchThreshold`.


I will fix it soon so that the drag can be maintained even when the pinch ends.

**Comment by daybrush** [comment]
@DerZade 

gesto 1.8.0 is released.

`keepDragging` option is added. you can set to `true`

**Comment by DerZade** [comment]
Works flawlessly!

Thank you very much for the quick update and the amazing library ❤️
