### ISSUE TITLE
Gesto does not fire `dragEnd`-Event, when `keepDragging` is enabled.

### ISSUE THREAD

**Issue by DerZade** [daybrush/gesto#5]
Gesto does not fire an `dragEnd`-Event, when the `keepDragging`-options is enabled and the user drags with a mouse.

**Comment by daybrush** [comment]
@DerZade 

oh this is my mistake Updated to 1.8.1.
Try it again. Thank you :)

**Comment by DerZade** [comment]
Works flawlessly! Thanks a lot for the blazingly fast fix ❤️
