### ISSUE TITLE
INPUT_TAGNAMES should be in all caps

### ISSUE THREAD

**Issue by longtengz** [daybrush/gesto#6]
`Element.tagName` in HTML returns tag name in upper case as described in https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName , but `INPUT_TAGNAMES` are all in lower case. So the following `indexOf` will always return `-1`

https://github.com/daybrush/gesto/blob/a6b1a07a749fa9d5da5898f5fd01fa42dd7c732f/src/Gesto.ts#L268

**Comment by daybrush** [comment]
@longtengz 

Thank you :)
A bug was fixed.

gesto's new version is released.

**Comment by longtengz** [comment]
That was quick. Thank you! Amazing stuff!
